controllers/GalleryController.php
<?php

namespace app\controllers;

use app\models\Image;
use app\models\Meta;
use Yii;
use app\models\Post;
use app\models\PostSearch;
use yii\data\Pagination;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use DataTime;

class GalleryController extends Controller
{
    public $layout = 'site';


    public function actionIndex(){
//        $meta = Meta::find()->where(['type' => 'news'])->one();

        $language = Yii::$app->language;
        $type = $_REQUEST['type'];

        $meta = $this->meta($type, $language);
        $title = $this->title($type);


        $posts = Post::find()->where(['type' => $type, 'lang' => $language, 'activity' => 1])->orderBy([
            'date' => SORT_DESC]);
        $pages = new Pagination(['totalCount' => $posts->count(), 'pageSize' =>6]);
        $post = $posts->offset($pages->offset)
            ->limit($pages->limit)
            ->all();

        return $this->render('index', compact('meta','post', 'title', 'pages'));
    }

    public function meta($type, $language){

        if($type == 0 ){
            $meta['title'] = Yii::t('common', 'TitleNews');
            $meta['keywords'] = Yii::t('common', 'keywordsNews');
            $meta['description'] = Yii::t('common', 'descriptionNews');


        }

        if($type == 1){

            $meta['title'] = Yii::t('common', 'TitleGallery');
            $meta['keywords'] = Yii::t('common', 'keywordsGallery');
            $meta['description'] = Yii::t('common', 'descriptionGallery');

        }
        return $meta;
    }
    public function actionShow(){

        $id = $_REQUEST['id'];
        $post = Post::find()->where(['id' => $id])->one();
        $meta = Meta::find()->where(['type' => $id])->one();

        if(!$meta){
            $meta = Meta::standartMeta();
        }
        $date = date($post->date);
        $language = Yii::$app->language;

        $date = dateFormat($language, $date);
        if($post->type == 0){
            $gallery = Post::find()->where(['id' => $post->gallery])->one();
            return $this->render('news', compact('meta', 'post', 'date', 'gallery'));
        }
        else{
            $query = Image::find()->where(['post_id' => $id, 'type' => $post->type]);
            $pages = new Pagination(['totalCount' => $query->count(), 'pageSize' => 9]);
            $post = $query->offset($pages->offset)
                ->limit($pages->limit)
                ->all();
            return $this->render('view', compact('meta', 'post', 'pages'));
        }

    }


    public function actionView(){

        $id = $_REQUEST['id'];
        $meta = Meta::find()->where(['type' => $id])->one();

        if(!$meta){
            $meta = Meta::standartMeta();
        }
        $type = $_REQUEST['type'];
        $query = Image::find()->where(['post_id' => $id, 'type' => $type]);
        $pages = new Pagination(['totalCount' => $query->count(), 'pageSize' => 9]);
        $post = $query->offset($pages->offset)
            ->limit($pages->limit)
            ->all();
        return $this->render('view', compact('meta','post', 'pages'));
    }


    protected function title($type){

        $type == 0 ? $title = Yii::t('common', 'news-title') : $title =Yii::t('common', 'gallery_title');
        return $title;
    }
}

views/gallery/gallery.php
<?php
/**
 * Created by PhpStorm.
 * User: Kirod
 * Date: 11.12.2018
 * Time: 19:45
 */
?>


gallery

views/gallery/index.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use app\widgets\LinkPager;
$this->title = $meta['title'];
$this->registerMetaTag(['name' => 'keywords', 'content' => $meta['keywords']]);
$this->registerMetaTag(['name' => 'description', 'content' => $meta['description']]);
?>

<div class="page-news-block-shape-left <? if (($_GET['type'])== 1): ?>page-news-block-shape-yellow<? endif; ?>"></div>
<div class="page-news-block-shape-right <? if (($_GET['type'])== 1): ?>page-news-block-shape-blue<? endif; ?>"></div>

<section class="page-news-area">
    <div class="container">
        <h1 class="text-heading"><?=$title?></h1>
        <div class="page-content-allnews">
            <div class="row">
                <?php foreach ($post as $value){?>
                <div class="col-lg-4 col-sm-6 col-xs-12">
                    <a class="single-main-news" href="/gallery/show?id=<?php echo $value->id?>">
                        <span class="block-image-news" style="background-image: url('/img/post/mini_<?php echo $value->short_img?>');"></span>
                        <span class="block-title-service">
                            <?= date('d.m.Y',$value->date);?>
                            <span class="title-main-news"><?= $value->title ?></span>
                        </span>
                    </a>
                </div>
                <?php }?>
            </div>
        </div>

        <div class="pagination_gallery">
            <?php echo LinkPager::widget([
                    'pagination' => $pages,
                    'pageCssClass' => 'pageClass',
                    'activePageCssClass' => 'currentPage',
                    'maxButtonCount' => 7,
                    'prevPageLabel' => '&lsaquo;',
                    'nextPageLabel' => '&rsaquo;',
                    'prevPageCssClass' => 'prev pageClass',
                    'nextPageCssClass' => 'next pageClass',
                    'activePageAsLink' => false,
                    'disableCurrentPageButton' => true,
                    'hideOnSinglePage' => true,
            ]); ?>
        </div>
    </div>
</section>

views/gallery/news.php
<?php
/**
 * Created by PhpStorm.
 * User: Kirod
 * Date: 11.12.2018
 * Time: 19:45
 */

use yii\helpers\Html;
use yii\helpers\Url;
$this->title = $meta->title;
$this->registerMetaTag(['name' => 'keywords', 'content' => "$meta->keywords"]);
$this->registerMetaTag(['name' => 'description', 'content' => $meta->description]);

?>

<div class="page-image-block page-news-image-block">
    <?= Html::img('/img/main/top-image.png'); ?>
</div>

<div class="page-block-yellow-shape"></div>
<div class="page-block-blue-shape"></div>
<div class="container container-page">
    <div class="container-page-wrapper">
        <h1 class="text-left title-page-txt"><?= ucfirst($post->title) ?></h1>
        <div class="block-data-news">
            <span class="block-news-city"><?= ucfirst($post->city) ?></span>
            <?= $date ?>
        </div>
        <div class="block-fulltxt-page">
            <p>
                <?= Html::img('/img/post/' . $post->short_img, ['class' => "img-fluid"]); ?>
            </p>
            <?= $post->full_text ?>
        </div>

        <?php if($gallery){?>
            <div class="block-news-gallery">
                <?= Html::img('/img/post/' . $gallery->short_img, ['class' => "img-fluid"]); ?>
                <?= Html::a('Перейти в галлерею', Url::toRoute(['/gallery/view', 'id' => $gallery->id, 'type' => $gallery->type]), ['class' => 'genric-btn more danger']); ?>
            </div>
        <?php }?>
    </div>
</div>

views/gallery/view.php
<?php

use app\widgets\LinkPager;
use yii\helpers\Html;
use yii\helpers\Url;

$this->title = $meta->title;
$this->registerMetaTag(['name' => 'keywords', 'content' => "$meta->keywords"]);
$this->registerMetaTag(['name' => 'description', 'content' => $meta->description]);

?>


<section class="page-news-area">
    <div class="container">
        <h1 class="text-heading"><?=Yii::t('common', 'gallery_title')?></h1>
        <div class="breadcrumb-block">
            <?=Html::a(Yii::t('common', 'album_title'), Url::toRoute(['/gallery/index', 'type' => '1']));?>
            <span class="breadcrumb-separator">/</span>
            <span><?=Yii::t('common', 'photo_title')?></span>
        </div>
        <div class="page-content-allimages">
            <div class="row">
                <?php foreach ($post as $img){?>
                    <div class="col-lg-4 col-sm-6 col-xs-6">
                        <a href="/img/allImages/<?=$img->img?>" class="img-pop-up"><span class="single-gallery-image" style="background: url(/img/allImages/<?=$img->img?>)"></span></a>
                    </div>
                <?php }?>
            </div>
        </div>

        <div class="pagination_gallery">
            <?php echo LinkPager::widget([
                    'pagination' => $pages,
                    'pageCssClass' => 'pageClass',
                    'activePageCssClass' => 'currentPage',
                    'maxButtonCount' => 7,
                    'prevPageLabel' => '&lsaquo;',
                    'nextPageLabel' => '&rsaquo;',
                    'prevPageCssClass' => 'prev pageClass',
                    'nextPageCssClass' => 'next pageClass',
                    'activePageAsLink' => false,
                    'disableCurrentPageButton' => true,
                    'hideOnSinglePage' => true,
            ]); ?>
        </div>
    </div>
</section>