models/Image.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "image".
 *
 * @property int $id
 * @property string $alt
 * @property int $type
 * @property int $post_id
 * @property string $img
 */
class Image extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'image';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['type', 'post_id'], 'integer'],
            [['img'], 'required'],
            [['img'], 'string', 'max' => 255],
            [['img'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'alt' => 'Alt',
            'type' => 'Type',
            'post_id' => 'Post ID',
            'img' => 'Img',
        ];
    }
}

controllers/ImagesController.php
<?php
namespace app\controllers;

use app\models\Image;
use Yii;
use app\models\Post;
use app\models\PostSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;


class ImagesController extends Controller
{

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ]
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }


    public function actionIndex(){
        $id = $_REQUEST['id'];
        $type = $_REQUEST['type'];
        $modelPost = new Post();
        $modelPost = $modelPost->find()->where(['id' => $id, 'type' => $type])->one();
        $model = new Image();
        $allImages = $model->find()->where(['post_id' => $id, 'type' => $type])->asArray()->all();
        return $this->render('index', compact('type', 'id', 'allImages', 'modelPost'));
        }


    public function actionDel(){

        $id = $_REQUEST['id'];


        $customer = Image::find()->where(['id' => $id])->one();
        unlink('img/allImages/'.$customer->img);
        $customer->delete();
        return ;
    }

    public function actionUpload()
    {



        $fileName = 'file';
        $uploadPath = Yii::$app->basePath.'/web/img/allImages';
        if (isset($_FILES[$fileName])) {

            $file = \yii\web\UploadedFile::getInstanceByName($fileName);

            $name = time().'.'.$file->extension;

            if ($file->saveAs($uploadPath . '/' . $name)) {
                $model = new Image();
                $model->post_id = $_REQUEST['id'];
                $model->type = $_REQUEST['type'];
                $model->img = $name;
                $model->save();
            }
        }

        return false;
    }

}

views/images/index.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use mihaildev\ckeditor\CKEditor;
use kato\DropZone;
use yii\helpers\Url;
use yii\widgets\Pjax;
?>

Загружать по 1-2 фотографии

<?php Pjax::begin(); ?>
<div class="imagesMain">
    <?php foreach($allImages as $img){?>
        <div class="images" id="img<?=$img['id']?>" >
            <?= Html::img('/img/allImages/'.$img['img'],["width"=>"200px"]);?>
            <div class="sel" ><a class="sel" onclick="deleteImage(<?=$img['id']?>) ">x</a></div>
        </div>


    <?php }?>
</div>

<div>
    <?= \kato\DropZone::widget([
        'id'        => 'dzImage', // <-- уникальные id
        'uploadUrl' => Url::toRoute([ '/images/upload', 'id' => $id, 'type' => $type ]),
        'dropzoneContainer' => 'dz-container-images', // <-- уникальные dropzoneContainer
        'previewsContainer' => 'preview-images', // <-- уникальные previewsContainer
        'options' => [
            'maxFiles' => '1',

        ],
        'clientEvents' => [
            'complete' => "function(file){console.log(file)}",
            'removedfile' => "function(file){alert(file.name + ' is removed')}"
        ],
    ]);?>
</div>

<?php Pjax::end();?>