models/Post.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "post".
 *
 * @property int $id
 * @property int $title
 * @property string $full_text
 * @property string $short_img
 * @property int $date
 * @property int $gallery
 * @property int $type
 * @property string $city
 * @property int $activity
 */
class Post extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'post';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['title',  'lang', 'full_text', 'type',], 'required'],
            [[  'type', 'activity'], 'integer'],
            [['full_text', 'short_img'], 'string'],
            [['city'], 'string', 'max' => 255],
            [['gallery'], 'safe'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'full_text' => 'Текст',
            'short_img' => 'Short Img',
            'full_img' => 'Full Img',
            'date' => 'Date',
            'type' => 'Type',
            'city' => 'City',
            'activity' => 'Activity',
        ];
    }
}

controllers/ImagesController.php
<?php
namespace app\controllers;

use app\models\Image;
use Yii;
use app\models\Post;
use app\models\PostSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;


class ImagesController extends Controller
{

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ]
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }


    public function actionIndex(){
        $id = $_REQUEST['id'];
        $type = $_REQUEST['type'];
        $modelPost = new Post();
        $modelPost = $modelPost->find()->where(['id' => $id, 'type' => $type])->one();
        $model = new Image();
        $allImages = $model->find()->where(['post_id' => $id, 'type' => $type])->asArray()->all();
        return $this->render('index', compact('type', 'id', 'allImages', 'modelPost'));
        }


    public function actionDel(){

        $id = $_REQUEST['id'];


        $customer = Image::find()->where(['id' => $id])->one();
        unlink('img/allImages/'.$customer->img);
        $customer->delete();
        return ;
    }

    public function actionUpload()
    {



        $fileName = 'file';
        $uploadPath = Yii::$app->basePath.'/web/img/allImages';
        if (isset($_FILES[$fileName])) {

            $file = \yii\web\UploadedFile::getInstanceByName($fileName);

            $name = time().'.'.$file->extension;

            if ($file->saveAs($uploadPath . '/' . $name)) {
                $model = new Image();
                $model->post_id = $_REQUEST['id'];
                $model->type = $_REQUEST['type'];
                $model->img = $name;
                $model->save();
            }
        }

        return false;
    }

}

controllers/PostController.php
<?php

namespace app\controllers;

use app\models\Meta;
use Imagine\Image\Box;
use Yii;
use app\models\Post;
use app\models\PostSearch;
use yii\base\Module;
use yii\imagine\Image;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * PostController implements the CRUD actions for Post model.
 */
class PostController extends Controller
{
    public $full_image;

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ]
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function __construct($id, Module $module, array $config = [])
    {
        parent::__construct($id, $module, $config);
        // Yii::$app->language = 'ru';

    }

    public function init()
    {
        parent::init();
        //  Yii::$app->language = 'ru';
        #add your logic: read the cookie and then set the language
    }

    /**
     * Lists all Post models.
     * @return mixed
     */
    public function actionNews()
    {

        $session = Yii::$app->session;
        $session->open();
        $session['page'] = 'news';


        $title = 'Список новостей';
        $searchModel = new PostSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, 0);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'title' => $title
        ]);
    }

    public function actionWinners()
    {
        $session = Yii::$app->session;
        $session->open();
        $session['page'] = 'winners';


        $title = 'Список Победителей';
        $searchModel = new PostSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, 4);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'title' => $title
        ]);
    }

    public function actionParticipants()
    {

        $session = Yii::$app->session;
        $session->open();
        $session['page'] = 'participants';

        $title = 'Список Участников';
        $searchModel = new PostSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, 5);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'title' => $title
        ]);
    }

    public function actionGallery()
    {
        $session = Yii::$app->session;
        $session->open();
        $session['page'] = 'gallery';

        $title = 'Список галерей';
        $searchModel = new PostSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, 1);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'title' => $title
        ]);
    }

    /**
     * Displays a single Post model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Post model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Post();
        $meta = new  Meta();
        $gallery = Post::find()->where(['type' => 1])->all();

        if ($model->load(Yii::$app->request->post())) {
            $session = Yii::$app->session;
            $session->open();
            if(isset(Yii::$app->request->post('Post')['date'])){
                $model->date = strtotime(Yii::$app->request->post('Post')['date']);
            }
            else{ $model->date = time();}

            if (isset($session['short_img'])) $model->short_img = $session['short_img'];

//            if (isset($session['full_img'])) $model->full_img = $session['full_img'];
            if ($model->save()) {

//

                $meta->saveMeta($model->id, $_REQUEST);
                unset($session['short_img']);
//                unset($session['full_img']);
                if($model->type == 1    ){

                    return $this->redirect(['update', 'id' => $model->id]);
                }
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('create', [
            'model' => $model, 'meta' => $meta, 'gallery' => $gallery
        ]);
    }


    public function actionProject()
    {
        $title = 'О проекте';
        $searchModel = new PostSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, 2);
        $session = Yii::$app->session;
        $session->open();
        $session['page'] = 'project';
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'title' => $title
        ]);

    }


    public function actionCondition()
    {

        $title = 'Условия участия';
        $searchModel = new PostSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, 3);
        $session = Yii::$app->session;
        $session->open();
        $session['page'] = 'condition';
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'title' => $title
        ]);
    }


    public function actionConditions()
    {

        $model = Post::find()->where(['type' => 3])->one();
        if ($model->load(Yii::$app->request->post())) {
            $session = Yii::$app->session;
            $session->open();
            $model->date = time();

            if (isset($session['short_img']) && $model->short_img != '') {
                if (file_exists('img/post/' . $model->short_img)) {
                    $handle = fopen('img/post/' . $model->short_img, 'r');
                    fclose($handle);
                    unlink('img/post/' . $model->short_img);

                }

                $model->short_img = $session['short_img'];
            }
            if ($model->save()) {
                unset($session['short_img']);
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }
        return $this->render('project', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Post model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {

        $meta = Meta::find()->where(['type' => $id])->one();
        if (!$meta) {
            $meta = new Meta();
        }
        $gallery = Post::find()->where(['type' => 1])->all();

        $model = $this->findModel($id);
//                print_r($model);


        if ($model->load(Yii::$app->request->post())) {
            $session = Yii::$app->session;
            $session->open();
            $model->date = strtotime(Yii::$app->request->post('Post')['date']);

            if (isset($session['short_img']) && $model->short_img != '') {
                if (file_exists('img/post/' . $model->short_img)) {
                    $handle = fopen('img/post/' . $model->short_img, 'r');
                    fclose($handle);
                    unlink('img/post/' . $model->short_img);
                }

            }
            if (isset($session['short_img'])) {
                $model->short_img = $session['short_img'];
            }

//            if (isset($session['full_img']) && $model->full_img != '') {
//                if (file_exists('img/post/' . $model->full_img)) {
//
//                    $handle = fopen('img/post/' . $model->full_img, 'r');
//                    fclose($handle);
//                    unlink('img/post/' . $model->full_img);
//
//                }
//
//                $model->full_img = $session['full_img'];
//            }

            if ($model->save()) {
                $meta->saveMeta($id, $_REQUEST);
                unset($session['short_img']);
//                unset($session['full_img']);
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('update', ['model' => $model, 'meta' => $meta, 'gallery' => $gallery]);
    }

    /**
     * Deletes an existing Post model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    { $session = Yii::$app->session;
        $session->open();


        $this->findModel($id)->delete();

        return $this->redirect('/post/'.$session['page']);
    }

    /**
     * Finds the Post model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Post the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Post::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

views/post/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use mihaildev\ckeditor\CKEditor;
use kato\DropZone;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $model app\models\Post */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="post-form">

    <?php $form = ActiveForm::begin(

            ['options' =>['enctype' =>'multipart/form-data'],
                'id' => 'post_id',
           ]
    ); ?>


    <?php echo $form->field($model, 'type')->label('Вид записи')->dropDownList([
        '0' => 'Новость',
        '1' => 'Галлерея',
        '2' => 'О проекте',
        '3' => 'Условия участия',
        '4' => 'Страница победителей',
        '5' => 'Страница участников',

    ],
            [
                'id' => 'type',
                'onchange' => 'changeSelect()',
            ]

    );?>

    <?php if($model->type ==0){
        $params = [
            'id' => 'gallery',
            'prompt' => 'Укажите галлерею для новости',
            'style' => 'display: block'
        ];
    }
    else{
        $params = [
            'id' => 'gallery',
            'style' => 'display: none'
        ];
    }
    ?>
    <?php  $items = ArrayHelper::map($gallery,'id','title');

    ?>
    <?=  $form->field($model, 'gallery')->dropDownList($items,$params)->label('');?>
    <?php echo $form->field($model, 'title')->textInput()->label('Заголовок страницы') ?>




    <?php echo  $form->field($model, 'full_text')->label('Полный текст')->widget(CKEditor::className(),[
        'editorOptions' => [
            'preset' => 'full', //разработанны стандартные настройки basic, standard, full данную возможность не обязательно использовать
            'inline' => false, //по умолчанию false
        ],
    ]);?>

    <div class="row">
        <div class="col-xs-12" >
            Изображение в списке
            <?php if($model->short_img != ''){?>
            <div>
                <?= Html::img('/img/post/'.$model->short_img,["width"=>"200px"]);?>
            </div>
            <?php }?>


            <?php echo \kato\DropZone::widget([
                'id'        => 'dzImage', // <-- уникальные id
                'uploadUrl' => Url::toRoute([ '/post/upload', 'id' => $model->id,'type' => '0' ]),
                'dropzoneContainer' => 'dz-container-images', // <-- уникальные dropzoneContainer
                'previewsContainer' => 'preview-images', // <-- уникальные previewsContainer
                'options' => [
                    'maxFilesize' => '10',
                ],
                'clientEvents' => [
                    'complete' => "function(file){console.log(file)}",
                    'removedfile' => "function(file){alert(file.name + ' is removed')}"
                ],
            ]);?>
        </div>

    </div>





    <?= $form->field($model, 'city')->label('Город')->textInput(['maxlength' => true]) ?>

    <?php echo $form->field($model, 'lang')->label('Язык')->dropDownList([
        'ru' => 'ru',
        'kz' => 'kz',

    ]);?>

    <?php echo $form->field($model, 'activity')->label('Статус')->dropDownList([
        '1' => 'Опубликованно',
        '0' => 'Отключено',

    ]);?>

    <?= $form->field($model, 'date')->label('Дата(необязательно)')->widget(\yii\jui\DatePicker::class, [
        'language' => 'ru',
        'dateFormat' => 'dd-MM-yyyy',
        'value'  => $model->date,
        'options' => ['class' => 'date'],
    ]) ?>



    <?php echo  $form->field($meta, 'title')->textInput();?>
    <?php echo  $form->field($meta, 'keywords')->textInput();?>
    <?php echo  $form->field($meta, 'description')->textInput();?>

    <div class="form-group">
        <?php echo Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/post/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\PostSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="post-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'title') ?>

<!--    --><?//= $form->field($model, 'short_text') ?>

    <?= $form->field($model, 'full_text') ?>

    <?= $form->field($model, 'short_img') ?>

    <?php // echo $form->field($model, 'full_img') ?>

    <?php // echo $form->field($model, 'date') ?>

    <?php // echo $form->field($model, 'type') ?>

    <?php // echo $form->field($model, 'city') ?>

    <?php // echo $form->field($model, 'activity') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/post/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Post */

$this->title = 'Создание Галлереи и новостей';
$this->params['breadcrumbs'][] = ['label' => 'Posts', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="post-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'meta' => $meta,
        'gallery' => $gallery
    ]) ?>

</div>

views/post/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\PostSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */


?>
 <div class="post-index">

    <h1><?= $title ?></h1>


    <p>
        <?= Html::a('Создать', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'options' => ['style' => 'width: 205px; max-width:205px; '],
         'layout'=>"{summary}\n{items}",
//
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],



            [
                'attribute'=>'title',
                'contentOptions' => ['style' => 'overflow-y: scroll;  
                 max-width: 400px;
                 max-height: 400px;
                 width: 100%;
                 height: 100%;'],
            ],


            'short_img:ntext',
            'lang:ntext',
            [

                'attribute' => 'date',

                'format' => ['date', 'd.M.y']

            ],
            'city',
            'activity',

            [
                'class' => \yii\grid\ActionColumn::className(),
                // you may configure additional properties here
            ],
        ],
    ]); ?>

    <div class="col-md-12 ">
        <div class="row margin20 ">

            <div class="pagination_gallery">

                <?php echo \app\widgets\LinkPager::widget([
                    'pagination' => $dataProvider->pagination,

                    'pageCssClass' => 'pageClass',
                    'activePageCssClass' => 'pageClass currentPage',
                    'maxButtonCount' => 7,
                    'prevPageLabel' => '&lsaquo;',

                    'nextPageLabel' => '&rsaquo;',
                    'prevPageCssClass' => 'prev',
                    'nextPageCssClass' => 'next',

                    'activePageAsLink' => false,
                    'disableCurrentPageButton' => true,
                    'hideOnSinglePage' => true,
                ]); ?>
            </div>
        </div>
    </div>
</div>

views/post/update.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\models\Post */

$this->title = 'Обновление новости или галлереи: ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Posts', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>

<div class="post-update">
    <?php if($model->type == 1){?>
    <?=Html::a('Загрузка фотографий', Url::toRoute(['/images/index', 'id' =>$model->id, 'type' => $model->type]));?>
    <?php }?>
    <h1><?= Html::encode($this->title) ?></h1>
    <?= $this->render('_form', [
        'model' => $model,
        'meta' => $meta,
        'gallery' => $gallery

    ]) ?>

</div>

views/post/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Post */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Posts', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="post-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Обновить', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'title',
            'full_text:ntext',
            'short_img:ntext',
            'date',
            'type',
            'city',
            'activity',
        ],
    ]) ?>

</div>