controllers/PostController.php
<?php

namespace app\controllers;

use app\models\Meta;
use Imagine\Image\Box;
use Yii;
use app\models\Post;
use app\models\PostSearch;
use yii\base\Module;
use yii\imagine\Image;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * PostController implements the CRUD actions for Post model.
 */
class PostController extends Controller
{
    public $full_image;

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ]
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function __construct($id, Module $module, array $config = [])
    {
        parent::__construct($id, $module, $config);
        // Yii::$app->language = 'ru';

    }

    public function init()
    {
        parent::init();
        //  Yii::$app->language = 'ru';
        #add your logic: read the cookie and then set the language
    }

    /**
     * Lists all Post models.
     * @return mixed
     */
    public function actionNews()
    {

        $session = Yii::$app->session;
        $session->open();
        $session['page'] = 'news';


        $title = 'Список новостей';
        $searchModel = new PostSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, 0);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'title' => $title
        ]);
    }

    public function actionWinners()
    {
        $session = Yii::$app->session;
        $session->open();
        $session['page'] = 'winners';


        $title = 'Список Победителей';
        $searchModel = new PostSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, 4);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'title' => $title
        ]);
    }

    public function actionParticipants()
    {

        $session = Yii::$app->session;
        $session->open();
        $session['page'] = 'participants';

        $title = 'Список Участников';
        $searchModel = new PostSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, 5);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'title' => $title
        ]);
    }

    public function actionGallery()
    {
        $session = Yii::$app->session;
        $session->open();
        $session['page'] = 'gallery';

        $title = 'Список галерей';
        $searchModel = new PostSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, 1);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'title' => $title
        ]);
    }

    /**
     * Displays a single Post model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Post model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Post();
        $meta = new  Meta();
        $gallery = Post::find()->where(['type' => 1])->all();

        if ($model->load(Yii::$app->request->post())) {
            $session = Yii::$app->session;
            $session->open();
            if(isset(Yii::$app->request->post('Post')['date'])){
                $model->date = strtotime(Yii::$app->request->post('Post')['date']);
            }
            else{ $model->date = time();}

            if (isset($session['short_img'])) $model->short_img = $session['short_img'];

//            if (isset($session['full_img'])) $model->full_img = $session['full_img'];
            if ($model->save()) {

//

                $meta->saveMeta($model->id, $_REQUEST);
                unset($session['short_img']);
//                unset($session['full_img']);
                if($model->type == 1    ){

                    return $this->redirect(['update', 'id' => $model->id]);
                }
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('create', [
            'model' => $model, 'meta' => $meta, 'gallery' => $gallery
        ]);
    }


    public function actionProject()
    {
        $title = 'О проекте';
        $searchModel = new PostSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, 2);
        $session = Yii::$app->session;
        $session->open();
        $session['page'] = 'project';
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'title' => $title
        ]);

    }


    public function actionCondition()
    {

        $title = 'Условия участия';
        $searchModel = new PostSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, 3);
        $session = Yii::$app->session;
        $session->open();
        $session['page'] = 'condition';
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'title' => $title
        ]);
    }


    public function actionConditions()
    {

        $model = Post::find()->where(['type' => 3])->one();
        if ($model->load(Yii::$app->request->post())) {
            $session = Yii::$app->session;
            $session->open();
            $model->date = time();

            if (isset($session['short_img']) && $model->short_img != '') {
                if (file_exists('img/post/' . $model->short_img)) {
                    $handle = fopen('img/post/' . $model->short_img, 'r');
                    fclose($handle);
                    unlink('img/post/' . $model->short_img);

                }

                $model->short_img = $session['short_img'];
            }
            if ($model->save()) {
                unset($session['short_img']);
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }
        return $this->render('project', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Post model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {

        $meta = Meta::find()->where(['type' => $id])->one();
        if (!$meta) {
            $meta = new Meta();
        }
        $gallery = Post::find()->where(['type' => 1])->all();

        $model = $this->findModel($id);
//                print_r($model);


        if ($model->load(Yii::$app->request->post())) {
            $session = Yii::$app->session;
            $session->open();
            $model->date = strtotime(Yii::$app->request->post('Post')['date']);

            if (isset($session['short_img']) && $model->short_img != '') {
                if (file_exists('img/post/' . $model->short_img)) {
                    $handle = fopen('img/post/' . $model->short_img, 'r');
                    fclose($handle);
                    unlink('img/post/' . $model->short_img);
                }

            }
            if (isset($session['short_img'])) {
                $model->short_img = $session['short_img'];
            }

//            if (isset($session['full_img']) && $model->full_img != '') {
//                if (file_exists('img/post/' . $model->full_img)) {
//
//                    $handle = fopen('img/post/' . $model->full_img, 'r');
//                    fclose($handle);
//                    unlink('img/post/' . $model->full_img);
//
//                }
//
//                $model->full_img = $session['full_img'];
//            }

            if ($model->save()) {
                $meta->saveMeta($id, $_REQUEST);
                unset($session['short_img']);
//                unset($session['full_img']);
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('update', ['model' => $model, 'meta' => $meta, 'gallery' => $gallery]);
    }

    /**
     * Deletes an existing Post model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    { $session = Yii::$app->session;
        $session->open();


        $this->findModel($id)->delete();

        return $this->redirect('/post/'.$session['page']);
    }

    /**
     * Finds the Post model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Post the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Post::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Main;
use app\models\Meta;
use app\models\Post;
use app\models\Questions;
use app\models\Registration;
use Yii;
use yii\data\Pagination;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use yii\web\UploadedFile;


class SiteController extends Controller
{
    public $layout = 'site';

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {


        return [

            'page' => [
                'class' => \yii\web\ViewAction::className(),
                'viewPrefix' => 'pages/' . \Yii::$app->language,
            ],
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $registration = new Registration();
        if ($registration->load(Yii::$app->request->post()) && $registration->validate()) {

            $registration->date = time();
            $registration->file = UploadedFile::getInstance($registration, 'file');
            if (!empty($registration->file)) {

                $registration->upload();


            }
            $registration->save();
            $registration = new Registration();

            return $this->redirect('/#submit-application');
        }
        $meta = Meta::find()->where(['type' => 'main'])->one();
        $type = 0;
        $titlePage = $this->titlePage($type);
        $languange = Yii::$app->language;
        $content = Main::find()->where(['lang' => $languange])->one();
//        pr($content);
        $post = Post::find()->where(['type' => $type, 'lang' => $languange, 'activity' => '1'])->orderBy([
            'date' => SORT_DESC])->one();
//        pr($post);
        $staticPage = $this->renderPartial('page', compact('content'));



        return $this->render('index', compact('meta','content','registration',  'titlePage', 'post', 'staticPage'));
    }


    public function actionProject()
    {

        $languange = Yii::$app->language;
        $model = Post::find()->where(['type' => 2, 'lang' => $languange, 'activity' => '1'])->one();
        $meta = Meta::find()->where(['type' => $model->id])->one();

        return $this->render('project', compact('model', 'meta'));
    }

    public function actionParticipants()
    {

        $languange = Yii::$app->language;
        $model = Post::find()->where(['type' => 5, 'lang' => $languange, 'activity' => '1'])->one();
        $meta = Meta::find()->where(['type' => $model->id])->one();
        return $this->render('participants', compact('model', 'meta'));
    }

    public function actionCondition()
    {

        $languange = Yii::$app->language;
        $model = Post::find()->where(['type' => 3, 'lang' => $languange, 'activity' => '1'])->one();
        $meta = Meta::find()->where(['type' => $model->id])->one();
        return $this->render('condition', compact('model', 'meta'));
    }


    public function actionWinners()
    {

        $languange = Yii::$app->language;
        $model = Post::find()->where(['type' => 4, 'lang' => $languange, 'activity' => '1'])->one();
        $meta = Meta::find()->where(['type' => $model->id])->one();

//        pr($model);
        return $this->render('winners', compact('model', 'meta'));
    }

    protected function titlePage($type)
    {

        $type == 0 ? $title = 'Архив новостей' : $title = 'Галлерея';
        return $title;
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }


    public function actionList()
    {
        $posts = Registration::find();
        $pages = new Pagination(['totalCount' => $posts->count(), 'pageSize' =>20]);
        $list = $posts->offset($pages->offset)
            ->limit($pages->limit)
            ->all();

        return $this->render('list', compact('list', 'pages'));

    }

    public function actionForm()
    {
        $registration = new Registration();


        if ($registration->load(Yii::$app->request->post())) {

            $registration->date = time();
            $registration->file = 'ddasa';
//            $registration->city =$_REQUEST['city'];

            $fileName = 'file';
            $uploadPath = Yii::$app->basePath . '/web/files/';
//            echo '<pre>';
//
//            print_r($_REQUEST);
//            die;
            if (isset($_FILES[$fileName])) {

                $file = \yii\web\UploadedFile::getInstanceByName($fileName);

                $name = time() . '.' . $file->extension;

                if ($file->saveAs($uploadPath . '/' . $name)) {

                    $registration->file = $name;
                }
            }
            $registration->save();
        }
        return $this->render('form', compact('registration'));
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionQuestion(){



        $languange = Yii::$app->language;
        $content = Questions::find() ->where(['lang' => $languange])->all();
//
        return $this->render('question', compact('content'));
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AdminAsset;

AdminAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
       

        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    $navItems=[

    ];
    if (Yii::$app->user->isGuest) {
        array_push($navItems,['label' => 'Sign In', 'url' => ['/user/login']]);
    } else {
        array_push($navItems,['label' => 'Logout (' . Yii::$app->user->identity->username . ')',
                'url' => ['/site/logout'],
                'linkOptions' => ['data-method' => 'post']]
        );
        array_push($navItems,['label' => 'Добавить новость', 'url' => ['/post']]);

    }

    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Новость', 'url' => ['/post/news']],
            ['label' => 'Галерея', 'url' => ['/post/gallery']],
            ['label' => 'Обновление главной', 'url' => ['/main']],
            ['label' => 'Мета', 'url' => ['/meta']],
            ['label' => 'Вопросы', 'url' => ['/questions']],
            ['label' => 'Регистрация участников', 'url' => ['/registration']],
            ['label' => 'O проекте', 'url' => ['/post/project']],
            ['label' => 'Условия участия', 'url' => ['/post/condition']],
            ['label' => 'Победители', 'url' => ['/post/winners']],
            ['label' => 'Список Участников', 'url' => ['/post/participants']],
            ['label' => 'Перейти на главную', 'url' => ['/site/index']],
//            ['label' => 'Contact', 'url' => ['/site/contact']],
            Yii::$app->user->isGuest ? (
            ['label' => 'Login', 'url' => ['/user/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/user/logout'], 'post')
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();


    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>

        <?= $content ?>
    </div>
</div>

<footer class="footer">

</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/site.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
use yii\helpers\Url;
AppAsset::register($this);
?>
<?php $this->beginPage() ?>

<!DOCTYPE html>

    <head>
    <meta charset="<?= Yii::$app->charset ?>">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <!-- Mobile Specific Meta -->
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Favicon-->

        <!-- Author Meta -->

        <!-- meta character set -->
        <meta charset="UTF-8">
        <!-- Site Title -->

        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css">

        <!--
        CSS
        ============================================= -->
        <?php $this->head() ?>
    </head>

    <body>
    <?php $this->beginBody() ?>

    <!--   -->
        <header>
            <div class="container">
                <div class="header-wrap">
                    <div class="header-top d-flex justify-content-between align-items-center">
                        <!--<div class="logo">
                            <a href="index.html"><img src="img/logo.png" alt=""></a>
                        </div>-->
                        <div class="main-menubar d-flex align-items-center">
                            <nav class="hide main-menubar-block">
                                <div class="menubar-language-block">
                                    <span class="footer-social">
                                        <a style="border-radius: 50%;" href="https://www.facebook.com/321startkz/"><i class="fa fa-facebook"></i></a><a style="border-radius: 50%;" href="https://vk.com/start321"><i class="fa fa-vk"></i></a><a style="border-radius: 50%;" href="https://www.youtube.com/channel/UCwLayHrpKfSFAKAwJs-FNYA/videos"><i class="fa fa-youtube-play"></i></a><a style="border-radius: 50%;" href="https://www.instagram.com/321_start/"><i class="fa fa-instagram"></i></a>
                                    </span>
                                    <?= $this->render('main/select') ?>
                                </div>
                                <div class="main-menubar-blocklink">
                                    <?=Html::a('<img class="main_logo" src="/img/main/321start-logo.png" title="">', Url::toRoute(['/site/index']), ['class'=>'logo']);?>
                                    <?=Html::a(Yii::t('common', 'about-project'), Url::toRoute(['/site/project']));?>
                                    <?=Html::a(Yii::t('common', 'condition_title'), Url::toRoute(['/site/condition']));?>
                                    <?=Html::a(Yii::t('common', 'participants'), Url::toRoute(['/site/participants']));?>
                                    <!--<?=Html::a(Yii::t('common', 'winners'), Url::toRoute(['/site/winners']));?>-->
                                    <a class="link-go-block" href="#submit-application"><?= Yii::t('common', 'apply-application')?></a>
                                    <?=Html::a(Yii::t('common', 'news-title'), Url::toRoute(['/gallery/index', 'type' => '0']));?>
                                    <?=Html::a(Yii::t('common', 'gallery_title'), Url::toRoute(['/gallery/index', 'type' => '1']));?>
                                    <?=Html::a(Yii::t('common', 'questions-and-answers'), Url::toRoute(['/site/question']));?>
                                    <a class="link-go-block" href="#block-contacts"><?= Yii::t('common', 'contacts-title')?></a>
                                </div>
                            </nav>
                            <div class="menu-bar"><span class="lnr lnr-menu"></span></div>
                        </div>
                    </div>
                </div>
            </div>
        </header>

    <div class="main-content-wrapper">
        <?=$content?>
        <!-- Start Feature Area -->


        <!-- End Service Area -->
        <!-- Start Amazing Works Area -->

            <footer>
                <div class="container">
                    <div class="footer_menu <?php if(Yii::$app->language == 'kz') echo "footer_menu_kz"; ?>">
                        <?=Html::a(Yii::t('common', 'main'), Url::toRoute(['/site/index']));?><?=Html::a(Yii::t('common', 'about-project'), Url::toRoute(['/site/project']));?>
                        <?=Html::a(Yii::t('common', 'condition_title'), Url::toRoute(['/site/condition']));?>
                        <?=Html::a(Yii::t('common', 'participants'), Url::toRoute(['/site/participants']));?>
                        <a class="link-go-block" href="#submit-application"><?= Yii::t('common', 'apply-application')?></a>
                        <?=Html::a(Yii::t('common', 'news-title'), Url::toRoute(['/gallery/index', 'type' => '0']));?>
                        <?=Html::a(Yii::t('common', 'gallery_title'), Url::toRoute(['/gallery/index', 'type' => '1']));?>
                        <?=Html::a(Yii::t('common', 'questions-and-answers'), Url::toRoute(['/site/question']));?>
                    </div>

                    <div class="footer-content d-flex justify-content-between align-items-center flex-wrap">
                        <div class="footer-phone-block" id="block-contacts">
                            <a class="footer-phone-link" target="_blank" rel="nofollow" href="tel:+7 (727) 250 60 96">+7 (727) 250 60 96 <span class="fa fa-phone"></span></a><a class="footer-phone-link" target="_blank" rel="nofollow" href="tel:+7 (727) 250 60 97">+7 (727) 250 60 97 <span class="fa fa-phone"></span></a>
                        </div>
                        <div class="footer-social-block">
                            <a target="_blank" rel="nofollow" href="mailto:hotline@cci.com.kz" class="footer-email-link">hotline@cci.com.kz</a>
                            <span class="footer-social">
                                <a style="border-radius: 50%;" href="https://www.facebook.com/321startkz/"><i class="fa fa-facebook"></i></a>
                                <a style="border-radius: 50%;" href="https://vk.com/start321"><i class="fa fa-vk"></i></a>
                                <a style="border-radius: 50%;" href="https://www.youtube.com/channel/UCwLayHrpKfSFAKAwJs-FNYA/videos"><i class="fa fa-youtube-play"></i></a>
                                <a style="border-radius: 50%;" href="https://www.instagram.com/321_start/"><i class="fa fa-instagram"></i></a>
                            </span>
                        </div>

                    </div>
                </div>
            </footer>
            <!-- End footer Area -->
    </div>

        <div class="modal fade" id="myModal">
                <div class="vertical-alignment-helper">
                    <div class="modal-dialog vertical-align-center">
                    <div class="modal-content text-center">
                        <div class="modal-content-wrapper">
                            <button type="button" class="close" data-dismiss="modal"><svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <g filter="url(#filter0_d)">
                                        <path fill-rule="evenodd" clip-rule="evenodd" d="M27 4.2L24.8 2L16 10.8L7.2 2L5 4.2L13.8 13L5 21.8L7.2 24L16 15.2L24.8 24L27 21.8L18.2 13L27 4.2Z" fill="white"/>
                                    </g>
                                    <defs>
                                        <filter id="filter0_d" x="0" y="0" width="32" height="32" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
                                            <feFlood flood-opacity="0" result="BackgroundImageFix"/>
                                            <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"/>
                                            <feOffset dy="3"/>
                                            <feGaussianBlur stdDeviation="2.5"/>
                                            <feColorMatrix type="matrix" values="0 0 0 0 0.929412 0 0 0 0 0.109804 0 0 0 0 0.109804 0 0 0 0.3 0"/>
                                            <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow"/>
                                            <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow" result="shape"/>
                                        </filter>
                                    </defs>
                                </svg>
                            </button>
                            <div class="modal-body">
                                <h2 class="text-heading text-center">Отлично!</h2>
                                <div class="text-center my-modal-text">Ваша заявка на участие принята. Ваша заявка на участие принята. Ваша заявка на участие принята.</div>
                            </div>
                            <button type="button" class="genric-btn more danger" data-dismiss="modal">Ок</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php $this->endBody() ?>
    </body>
</html>
<?php $this->endPage() ?>